[project]
name = "custom-rss-feed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "curl-cffi>=0.13.0",
    "rfeed>=1.1.1",
    "tenacity>=9.1.2",
]
